---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/uschti/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Development/github.com/uschti/dotfiles
dotfiles_files:
  - .aliases
  - .ansible.cfg
  - .bash_profile
  - .bash_promt
  - .exports
  - .functions
  - .gitconfig
  - .gitignore
  - .hushlogin
  - .inputrc
  - .macos
  - .screenrc
  - .tmux.conf
  - .wgetrc

homebrew_installed_packages:
  - autoconf
  - bash-completion
  - cookiecutter
  - cowsay
  - diff-so-fancy
  - dos2unix
  - eclipse-java
  - fd # alternative to find: https://github.com/sharkdp/fd
  - ffmpeg
  - gcc
  - git
  - gpg
  - htop
  - httpie
  - iperf
  - mas
  - nmap
  - node
  - npm
  - openshift-cli
  - openssl
  - python3
  - ripgrep # fast search, replace `pt`
  - ruby # overrite the default installation
  - source-to-image
  - speedtest-cli
  - ssh-copy-id
  - stormssh
  - terraform
  - thefuck
  - wget
  - wrk
  - youtube-dl

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - java8
  - android-file-transfer
  - android-sdk
  - angry-ip-scanner
  - atom
  - bitbar
  - caffeine
  - calibre
  - cyberduck
  - dash
  - docker
  - firefox
  - gimp
  - google-chrome
  - go2shell
  - handbrake
  - image2icon
  - istat-menus
  - jd-gui
  - keepassxc
  - keka
  - keystore-explorer
  - kitematic
  - libreoffice
  - mamp
  - mattermost
  - mysqlworkbench
  - nextcloud
  - nvalt
  - pgadmin4
  - postman
  - powershell
  - skitch
  - sketch
  - skype
  - slack
  - soapui
  - sourcetree
  - sublime-text
  - thunderbird
  - tunnelblick
  - vmware-fusion
  - veracrypt
  - vlc
  - vnc-viewer
  - whatsapp
  - wireshark
  - youtube-to-mp3

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 692867256, name: "Simplenote (1.1.8)"}
  - { id: 497799835, name: "Xcode (9.3)"}
  - { id: 409183694, name: "Keynote (7.3.1)"}
  - { id: 409203825, name: "Numbers (5.0)"}
  - { id: 452695239, name: "QREncoder (1.5)"}
  - { id: 409201541, name: "Pages (7.0)"}
  - { id: 404010395, name: "TextWrangler (5.5.2)"}
  - { id: 458887729, name: "Translate Tab (2.0.1)"}

mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Create some useful directory structures
required_directories:
  - "~/.venvs"
  - "~/.ansible/roles"
  - "~/cloud"
  - "~/Development"
  - "~/Docker_workspace"
  - "~/git"
  - "~/eclipse"
  - "~/eclipse-workspace"
  - "~/Servers"
  - "~/tmp_projects"
  - "~/VM"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages:
  - ionic
  - cordova

pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
