---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/uschti/dotfiles.git # ok
dotfiles_repo_accept_hostkey: yes # ok
dotfiles_repo_local_destination: ~/Development/github.com/uschti/dotfiles
dotfiles_files:
  - .aliases
  - .ansible.cfg
  - .bash_profile
  - .bash_promt
  - .exports
  - .functions
  - .gitconfig
  - .gitignore
  - .hushlogin
  - .inputrc
  - .macos
  - .screenrc
  - .tmux.conf
  - .wgetrc

homebrew_installed_packages:
  - autoconf # ok
  - bash-completion # ok
  - cookiecutter # ok
  - cowsay # ok
  - diff-so-fancy # ok
  - dos2unix # ok
  - eclipse-java # ok
  - fd # alternative to find: https://github.com/sharkdp/fd
  - ffmpeg # ok
  - gcc # ok
  - git # ok
  - gpg # ok
  - htop # ok
  - httpie # ok
  - iperf # ok
  - mas # ok
  - nmap # ok
  - node # ok
  - npm # ok
  - openshift-cli # ok
  - openssl # ok
  - python3 # ok
  - ripgrep # fast search, replace `pt`
  - ruby # overrite the default installation
  - source-to-image # ok
  - speedtest-cli # ok
  - ssh-copy-id # ok
  - stormssh # ok
  - terraform # ok
  - thefuck # ok
  - wget # ok
  - wrk # ok
  - youtube-dl # ok

homebrew_taps:
  - homebrew/core # ok
  - caskroom/cask # ok
  - homebrew/binary # ok
  - homebrew/dupes # ok
  - homebrew/versions # ok

homebrew_cask_appdir: /Applications # ok
homebrew_cask_apps:
  - java8 # ok
  - android-file-transfer # ok
  - android-sdk # ok
  - angry-ip-scanner # ok
  - atom # ok
  - bitbar # ok
  - caffeine # ok
  - calibre # ok
  - cyberduck # ok
  - dash # ok
  - docker # ok
  - firefox # ok
  - gimp # ok
  - google-chrome # ok
  - go2shell # ok
  - handbrake # ok
  - image2icon # ok
  - istat-menus # ok
  - jd-gui # ok
  - keepassxc # ok
  - keka # ok
  - keystore-explorer # ok
  - kitematic # ok
  - libreoffice # ok
  - mamp # ok
  - mattermost # ok
  - mysqlworkbench # ok
  - nextcloud # ok
  - nvalt # ok
  - pgadmin4 # ok
  - postman # ok
  - powershell # ok
  - skitch # ok
  - sketch # ok
  - skype # ok
  - slack # ok
  - soapui # ok
  - sourcetree # ok
  - sublime-text # ok
  - thunderbird # ok
  - tunnelblick # ok
  - vmware-fusion # ok
  - veracrypt # ok
  - vlc # ok
  - vnc-viewer # ok
  - whatsapp # ok
  - wireshark # ok
  - youtube-to-mp3 # ok

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 692867256, name: "Simplenote (1.1.8)"} # ok
  - { id: 497799835, name: "Xcode (9.3)"} # ok
  - { id: 409183694, name: "Keynote (7.3.1)"} # ok
  - { id: 409203825, name: "Numbers (5.0)"} # ok
  - { id: 452695239, name: "QREncoder (1.5)"} # ok
  - { id: 409201541, name: "Pages (7.0)"} # ok
  - { id: 404010395, name: "TextWrangler (5.5.2)"} # ok
  - { id: 458887729, name: "Translate Tab (2.0.1)"} # ok

mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Create some useful directory structures
required_directories:
  - "~/.venvs"
  - "~/.ansible/roles"
  - "~/cloud"
  - "~/Development"
  - "~/Docker_workspace"
  - "~/git"
  - "~/eclipse"
  - "~/eclipse-workspace"
  - "~/Servers"
  - "~/tmp_projects"
  - "~/VM"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages:
  - ionic
  - cordova

pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
